### ISSUE TITLE
Issue with rotation plots when 2 coils have been excluded

### ISSUE THREAD

**Issue by hannahrapaport** [Macquarie-MEG-Research/MQ_MEG_Scripts#16]
Regarding the 'process_ME175' script', the rotation plots look strange when 2 bad coils have been excluded (i.e., the entire graph is blocked-out/shaded). Example attached. 

bad
<img width="320" alt="Screen Shot 2019-09-10 at 4 55 49 pm" src="https://user-images.githubusercontent.com/39174545/64590873-e12b5700-d3eb-11e9-89ff-8b7a27093cd2.png">

vs

good

<img width="383" alt="Screen Shot 2019-09-10 at 4 59 26 pm" src="https://user-images.githubusercontent.com/39174545/64591170-86dec600-d3ec-11e9-8d97-6794a7f380e2.png">

**Comment by neurofractal** [comment]
Thanks @hannahrapaport - it seems like the function is hardcoded to use rot3dfit. Tomorrow I'll try changing this to ICP.

```matlab
for i = 1:length(head_movt.pos)
    try
    [R,T,Yf,Err]    = rot3dfit(squeeze(head_movt.pos(1,:,:)),...
            squeeze(head_movt.pos(i,:,:)));%calc rotation transform
    meg2head_transm = [[R;T]'; 0 0 0 1];%reorganise and make 4*4 transformation matrix
                
    fiducials_over_time(i,:,:,:) = ft_warp_apply(meg2head_transm,...
    headshape.fid.pos);
    catch
        fiducials_over_time(i,:,:,:) = nan(3);
    end
end
```

**Comment by hannahrapaport** [comment]
It's working! Thanks a million!
