### ISSUE TITLE
IDEA: simulate facial info for old data

### ISSUE THREAD

**Issue by neurofractal** [Macquarie-MEG-Research/MQ_MEG_Scripts#17]
An idea: for data where no facial information was digitised, could we 'simulate' vague facial points in order to help with the coreg? This could be based on the nasion & come from existing .hsp data with facial info (perhaps averaged?). I think this would especially benefit MEMES. It seems a little hacky, but might work!

**Comment by neurofractal** [comment]
Seems to improve things for some subjects (!) TOP = with facial info added ; BOTTOM = without facial info. @paulsowman :)

![sourceI_new3](https://user-images.githubusercontent.com/18535653/64747947-ea373800-d553-11e9-93c7-55d7fb202912.png)
![sourceI](https://user-images.githubusercontent.com/18535653/64747949-eacfce80-d553-11e9-987e-248b155ff92d.png)

**Comment by paulsowman** [comment]
Indeed, this looks good. Seems consistent with the forward tilt we sometimes get. P
