### ISSUE TITLE
Output files from mq_con2fif_maxfilter.py

### ISSUE THREAD

**Issue by JD-Zhu** [Macquarie-MEG-Research/MQ_MEG_Scripts#18]
Hi Robert,

I just tried out this new version :) It produces two output files:
_raw_tsss.fif
_raw_tsss-1.fif

Just wondering what is the difference between these two files, and which one should we use? The "_raw_tsss-1.fif" seems to have a much smaller file size.

Thanks,
Judy

**Comment by JD-Zhu** [comment]
An additional question:
When reference sensor data are available, should noise reduction (CALM/TSPCA) be performed prior to tSSS?

Thanks,
Judy

**Comment by JD-Zhu** [comment]
Ok, I can now answer the first question. The dataset was split into 2 output files because it was too large (this happens when the recording length exceeds 35 minutes). We just need to join the 2 output files together.

> Hi Robert,
> 
> I just tried out this new version :) It produces two output files:
> _raw_tsss.fif
> _raw_tsss-1.fif
> 
> Just wondering what is the difference between these two files, and which one should we use? The "_raw_tsss-1.fif" seems to have a much smaller file size.
> 
> Thanks,
> Judy

**Comment by neurofractal** [comment]
> Ok, I can now answer the first question. The dataset was split into 2 output files because it was too large (this happens when the recording length exceeds 35 minutes). We just need to join the 2 output files together.
> 
> > Hi Robert,
> > I just tried out this new version :) It produces two output files:
> > _raw_tsss.fif
> > _raw_tsss-1.fif
> > Just wondering what is the difference between these two files, and which one should we use? The "_raw_tsss-1.fif" seems to have a much smaller file size.
> > Thanks,
> > Judy

Indeed - maximum size of .fif files are 2GB I believe. 

> An additional question:
> When reference sensor data are available, should noise reduction (CALM/TSPCA) be performed prior to tSSS?

Mmm good question. I wouldn't use them together for the same dataset.

- tSSS needs be performed on raw data, for spherical harmonic functions to be valid

- But alternatively using CALM/TSPCA after tSSS, I also don't think it makes sense to project components out of your data which have been already removed by tSSS.

Thoughts @paulsowman ?
