### ISSUE TITLE
mq_detect_saturations - stuck in loop?

### ISSUE THREAD

**Issue by JD-Zhu** [Macquarie-MEG-Research/MQ_MEG_Scripts#8]
Hi Robert,

I am running mq_detect_saturations on a 1.5G con file, and it has been running for close to 2 hours. Does it usually take that long? Just wondering if I might be stuck in an infinite loop or something. 

Thanks,
Judy

**_Last few lines of console output:_**

reading and preprocessing trial 1 from 1

the call to "ft_preprocessing" took 50 seconds
the call to "ft_selectdata" took 2 seconds
Searching the data channel by channel for signal saturation...

**Comment by neurofractal** [comment]
1.5GB is a very large file! It may just take this long, although my 500MB ones run in 2-3 mins. Try running this new version which reports the progress: https://github.com/Macquarie-MEG-Research/MQ_MEG_Scripts/commit/1ef8d865bc1343a8bffcc16dcf48ae464be2b141

**Comment by JD-Zhu** [comment]
Thanks Robert! Running the new version now. So far it looks like each channel takes ~15 minutes.

**Comment by neurofractal** [comment]
This seems very long (!) ... there's probably a way to speed things up. Leave it with me. 

When you run:

```matlab
disp('Loading data');
% Epoch the whole dataset into one continous dataset and apply
% the appropriate filters
cfg = [];
cfg.headerfile = confile;
cfg.datafile = confile;
cfg.trialdef.triallength = Inf;
cfg.trialdef.ntrials = 1;
cfg = ft_definetrial(cfg);

cfg.continuous = 'yes';
alldata = ft_preprocessing(cfg);
```
How large is alldata.trial{1,1}?

**Comment by JD-Zhu** [comment]
256x2967000

**Comment by neurofractal** [comment]
Hi @JD-Zhu with that size matrix (of random numbers) I'm getting 4-5 seconds per channel. Could you try the code below & report back?

```matlab

sat = [];
count = 1;

disp('Searching the data channel by channel for signal saturation...');
for i = 1:length(alldata.label)
    tic
    % Use regular expressions to get the index and number of
    % repetitions in the signal
    [time_id, number_N] = regexp(regexprep(num2str...
        (~diff(alldata.trial{1,1}(i,:))),' ','')...
        ,'1+','start','match');
    
    % Convert from cell to ?
    number_N = cellfun('length',number_N);
    
    % If any of the repetitions are over min_length
    if any(number_N>min_length*alldata.fsample)
        
        % Add channel to sat label
        fprintf('%10s saturations = YES \n',alldata.label{i,1});
        sat.label{count,1} = alldata.label{i,1};
        
        % Find the indices of the saturations
        number_N_over = find(number_N>min_length*alldata.fsample);
        
        time_data = alldata.time{1,1}(1,:);
        
        % Make .time field in sat
        sat.time{count,1} = [];
        
        % For every saturation
        for r = 1:length(number_N_over)
            
            % Get the index of the saturations
            time_of_sat = time_id(number_N_over(r));
            
            % Get the time (in sec) of the saturation
            time_of_sat_sec = time_data(time_of_sat:time_of_sat+...
                number_N(number_N_over(r)));
            
            % Add this to the .time field
            sat.time{count,1} = [sat.time{count,1}, time_of_sat_sec];
        end
        
        count = count+1;
    else
     fprintf('%10s saturations = NO \n',alldata.label{i,1});
    end
    toc
    
    
end
```

**Comment by JD-Zhu** [comment]
Still running ... will report back tomorrow!

**Comment by JD-Zhu** [comment]
Searching the data channel by channel for signal saturation...
     AG001 saturations = NO 
Elapsed time is 832.396817 seconds.
     AG002 saturations = NO 
Elapsed time is 829.167915 seconds.
     AG003 saturations = NO 
Elapsed time is 828.584777 seconds.
     AG004 saturations = NO 
Elapsed time is 828.783377 seconds.
     AG005 saturations = NO 
Elapsed time is 830.985776 seconds.

**Comment by neurofractal** [comment]
Weird! @JD-Zhu Would you mind uploading the data on cloudstor so I can check if it's a data issue or computer issue? Could potentially be due to different MATLAB versions as well.

**Comment by JD-Zhu** [comment]
I am having trouble uploading to Cloudstor. Tried a few different files, but kept getting the "chunks on server do not sum up to ..." error. I will bring it to you on a hard drive.

I'm running Matlab R2014b.

**Comment by paulsowman** [comment]
Could you try uploading smaller chunks as a test? Say 2-3 GB. P

**Comment by neurofractal** [comment]
Ok the earlier MATLAB version might be the reason. I'll be in my office
tomorrow :)

**Comment by paulsowman** [comment]
If you really need 2014b you can always install another (newer!) version in parallel. P

**Comment by JD-Zhu** [comment]
Just tried in 2017b and seems to be much faster ( 9 seconds per channel). Thank you!

Also the cloudstor upload finally succeeded, but I guess we don't need that now :)

**Comment by neurofractal** [comment]
Thanks - I'll keep this open & work out what to do for earlier versions!

**Comment by neurofractal** [comment]
@JD-Zhu please see https://github.com/Macquarie-MEG-Research/MQ_MEG_Scripts/commit/97f12ac2c87dc3ecc9a9a9d2ca8813c723ff645d

New method 'array' works much faster than the string comparison method. Will close this - please raise an issue if you find bugs in the new method :)
